n1= int(input('um valor:'))
n2= int(input('Digite outro valor:'))
s=(n1+n2)
m=(n1*n2)
d=(n1/n2)
di=(n1//n2)
e=(n1**n2)
print('A soma é {},\n a multiplicação é {}, a divisao é {:.3f}.'.format(s, m, d), end=' ')
print('A divisão inteira {} e potencia {}'. format(di, e))
